- name: ansible data types
  hosts: local
  connection: local
  vars:
   COURSE: "DevOps with aws" #this is string
   DURATION: 20hrs #this is number
   IS_LIVE: true #this is boolean
   TOOLS: #this is list []
      - ansible
      - terraform
      - docker
   CONCEPTS: # map or dictionary or object. referred like {}   
    CI: jenkins
    SCRIPTING: "shell,ansible,terraform,python"
  tasks:
   - name: print course information
     ansible.builtin.debug:
       msg: "Course is {{ COURSE }}, Duration is {{ DURATION }}, Is Live?: {{ IS_LIVE }}, Tools: {{ TOOLS }}, Concepts: {{ CONCEPTS }}"  
