- name: functions
  hosts: local
  connection: local
  vars:
   persons: "Ravi,Geetha,Usha,Venu"
  tasks:
   - name: check undefined variable
     ansible.builtin.debug:
      msg: "hello {{ person | default('venu') }}" 
      #if person is not defined then it will take venu as default value

   - name: print names
     ansible.builtin.debug:
      msg: "hello {{ persons | split(',') }}"   

   - name: convert map into list
     vars:
      course:
       name: "Ansible"
       duration: "2 months"
       trainer: "Venu"
     ansible.builtin.debug:
      msg: "course info: {{ course | dict2items }}"

   - name: convert list into map
     vars:
      course_list:
       - {'key': 'name', 'value': 'Ansible'}
       - {'key': 'duration', 'value': '2 months'}
       - {'key': 'trainer', 'value': 'Venu'}       
     ansible.builtin.debug:
      msg: "course info: {{ course_list | items2dict }}"
         
         