- name: install nginx
  hosts: dynamic_frontend
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.dnf:
     name: nginx
     state: installed
  - name: run nginx
    ansible.builtin.service:
     name: naginx
     state: started
     enabled: yes